// frontend/lib/layer-metadata.ts
/**
 * Static layer metadata registry for data transparency.
 *
 * Maps every frontend layer key to its data source, type, update interval,
 * and license information. Used by DataTypeBadge, DataSourceSection, and
 * the sidebar to display transparency info.
 */

export type DataType = 'LIVE' | 'SCRAPED' | 'INTERPOLATED' | 'MODELED' | 'STATIC';

export interface LayerMetadataEntry {
  layerKey: string;
  sourceName: string;
  sourceUrl: string;
  dataType: DataType;
  updateIntervalSeconds: number | null;
  license: string;
  licenseUrl: string;
  sourceAbbrev: string;
}

export const DATA_TYPE_COLORS: Record<DataType, string> = {
  LIVE: '#22c55e',
  SCRAPED: '#eab308',
  INTERPOLATED: '#3b82f6',
  MODELED: '#a855f7',
  STATIC: '#6b7280',
};

export const DATA_TYPE_LABELS: Record<DataType, string> = {
  LIVE: 'LIVE',
  SCRAPED: 'SCRAPED',
  INTERPOLATED: 'INTERPOLATED',
  MODELED: 'MODELED',
  STATIC: 'STATIC',
};

export const LAYER_METADATA: Record<string, LayerMetadataEntry> = {
  transit: {
    layerKey: 'transit',
    sourceName: 'MobiData BW / NVBW GTFS',
    sourceUrl: 'https://www.mobidata-bw.de/',
    dataType: 'LIVE',
    updateIntervalSeconds: 1800,
    license: 'Datenlizenz Deutschland \u2013 Namensnennung \u2013 Version 2.0',
    licenseUrl: 'https://www.govdata.de/dl-de/by-2-0',
    sourceAbbrev: 'NVBW',
  },
  busPosition: {
    layerKey: 'busPosition',
    sourceName: 'NVBW GTFS (interpoliert)',
    sourceUrl: 'https://www.nvbw.de/',
    dataType: 'INTERPOLATED',
    updateIntervalSeconds: 30,
    license: 'Datenlizenz Deutschland \u2013 Namensnennung \u2013 Version 2.0',
    licenseUrl: 'https://www.govdata.de/dl-de/by-2-0',
    sourceAbbrev: 'NVBW',
  },
  airQuality: {
    layerKey: 'airQuality',
    sourceName: 'UBA + Sensor.Community',
    sourceUrl: 'https://www.umweltbundesamt.de/',
    dataType: 'LIVE',
    updateIntervalSeconds: 300,
    license: 'Datenlizenz Deutschland \u2013 Namensnennung \u2013 Version 2.0',
    licenseUrl: 'https://www.govdata.de/dl-de/by-2-0',
    sourceAbbrev: 'UBA',
  },
  airQualityGrid: {
    layerKey: 'airQualityGrid',
    sourceName: 'IDW Interpolation',
    sourceUrl: 'https://sensor.community/',
    dataType: 'INTERPOLATED',
    updateIntervalSeconds: 300,
    license: 'Computed from UBA + Sensor.community data',
    licenseUrl: 'https://www.govdata.de/dl-de/by-2-0',
    sourceAbbrev: 'UBA',
  },
  water: {
    layerKey: 'water',
    sourceName: 'PEGELONLINE (WSV / BfG)',
    sourceUrl: 'https://www.pegelonline.wsv.de/',
    dataType: 'LIVE',
    updateIntervalSeconds: 900,
    license: 'Datenlizenz Deutschland \u2013 Zero \u2013 Version 2.0',
    licenseUrl: 'https://www.govdata.de/dl-de/zero-2-0',
    sourceAbbrev: 'PEGELONLINE',
  },
  kocher: {
    layerKey: 'kocher',
    sourceName: 'LHP Baden-Wuerttemberg',
    sourceUrl: 'https://www.hvz.baden-wuerttemberg.de/',
    dataType: 'LIVE',
    updateIntervalSeconds: 900,
    license: 'Datenlizenz Deutschland',
    licenseUrl: 'https://www.govdata.de/dl-de/by-2-0',
    sourceAbbrev: 'LHP',
  },
  traffic: {
    layerKey: 'traffic',
    sourceName: 'BASt (Bundesanstalt fuer Strassenwesen)',
    sourceUrl: 'https://www.bast.de/',
    dataType: 'LIVE',
    updateIntervalSeconds: 3600,
    license: 'Datenlizenz Deutschland - Zero - Version 2.0',
    licenseUrl: 'https://www.govdata.de/dl-de/zero-2-0',
    sourceAbbrev: 'BASt',
  },
  trafficFlow: {
    layerKey: 'trafficFlow',
    sourceName: 'TomTom',
    sourceUrl: 'https://developer.tomtom.com/',
    dataType: 'LIVE',
    updateIntervalSeconds: 600,
    license: 'TomTom Developer License',
    licenseUrl: 'https://developer.tomtom.com/',
    sourceAbbrev: 'TomTom',
  },
  autobahn: {
    layerKey: 'autobahn',
    sourceName: 'Autobahn GmbH des Bundes',
    sourceUrl: 'https://verkehr.autobahn.de/',
    dataType: 'LIVE',
    updateIntervalSeconds: 300,
    license: 'Datenlizenz Deutschland - Zero - Version 2.0',
    licenseUrl: 'https://www.govdata.de/dl-de/zero-2-0',
    sourceAbbrev: 'Autobahn',
  },
  energy: {
    layerKey: 'energy',
    sourceName: 'SMARD (Bundesnetzagentur)',
    sourceUrl: 'https://www.smard.de/',
    dataType: 'LIVE',
    updateIntervalSeconds: 900,
    license: 'Datenlizenz Deutschland - Zero - Version 2.0',
    licenseUrl: 'https://www.govdata.de/dl-de/zero-2-0',
    sourceAbbrev: 'SMARD',
  },
  solarGlow: {
    layerKey: 'solarGlow',
    sourceName: 'Computed from MaStR + Bright Sky',
    sourceUrl: 'https://brightsky.dev/',
    dataType: 'MODELED',
    updateIntervalSeconds: 900,
    license: 'Datenlizenz Deutschland / CC BY 4.0',
    licenseUrl: 'https://www.govdata.de/dl-de/by-2-0',
    sourceAbbrev: 'MaStR',
  },
  evCharging: {
    layerKey: 'evCharging',
    sourceName: 'MobiData BW OCPDB',
    sourceUrl: 'https://ocpdb.2hat.de/',
    dataType: 'LIVE',
    updateIntervalSeconds: 300,
    license: 'Open data',
    licenseUrl: 'https://www.mobidata-bw.de/',
    sourceAbbrev: 'OCPDB',
  },
  parking: {
    layerKey: 'parking',
    sourceName: 'Stadtwerke Aalen',
    sourceUrl: 'https://www.sw-aalen.de',
    dataType: 'SCRAPED',
    updateIntervalSeconds: 600,
    license: 'scraping',
    licenseUrl: 'https://www.sw-aalen.de',
    sourceAbbrev: 'SW-Aalen',
  },
  roadworks: {
    layerKey: 'roadworks',
    sourceName: 'OpenStreetMap contributors',
    sourceUrl: 'https://www.openstreetmap.org/copyright',
    dataType: 'LIVE',
    updateIntervalSeconds: 3600,
    license: 'ODbL 1.0',
    licenseUrl: 'https://opendatacommons.org/licenses/odbl/',
    sourceAbbrev: 'OSM',
  },
  heatDemand: {
    layerKey: 'heatDemand',
    sourceName: 'KEA-BW Waermeatlas (simulated)',
    sourceUrl: 'https://www.kea-bw.de/waermeatlas',
    dataType: 'MODELED',
    updateIntervalSeconds: null,
    license: 'Datenlizenz Deutschland \u2013 Namensnennung \u2013 Version 2.0',
    licenseUrl: 'https://www.govdata.de/dl-de/by-2-0',
    sourceAbbrev: 'KEA-BW',
  },
  cycling: {
    layerKey: 'cycling',
    sourceName: 'OpenStreetMap (cycling)',
    sourceUrl: 'https://www.openstreetmap.org/',
    dataType: 'STATIC',
    updateIntervalSeconds: null,
    license: 'ODbL 1.0',
    licenseUrl: 'https://opendatacommons.org/licenses/odbl/',
    sourceAbbrev: 'OSM',
  },
  demographics: {
    layerKey: 'demographics',
    sourceName: 'Statistisches Bundesamt, Zensus 2022',
    sourceUrl: 'https://www.zensus2022.de/',
    dataType: 'STATIC',
    updateIntervalSeconds: null,
    license: 'Datenlizenz Deutschland \u2013 Namensnennung \u2013 Version 2.0',
    licenseUrl: 'https://www.govdata.de/dl-de/by-2-0',
    sourceAbbrev: 'Zensus',
  },
  roadNoise: {
    layerKey: 'roadNoise',
    sourceName: 'LUBW Baden-Wuerttemberg',
    sourceUrl: 'https://www.lubw.baden-wuerttemberg.de/',
    dataType: 'MODELED',
    updateIntervalSeconds: null,
    license: 'Datenlizenz Deutschland \u2013 Namensnennung \u2013 Version 2.0',
    licenseUrl: 'https://www.govdata.de/dl-de/by-2-0',
    sourceAbbrev: 'LUBW',
  },
  fernwaerme: {
    layerKey: 'fernwaerme',
    sourceName: 'Stadtwerke Aalen',
    sourceUrl: 'https://www.sw-aalen.de',
    dataType: 'STATIC',
    updateIntervalSeconds: null,
    license: 'Proprietary',
    licenseUrl: 'https://www.sw-aalen.de',
    sourceAbbrev: 'SW-Aalen',
  },
  schools: {
    layerKey: 'schools',
    sourceName: 'OpenStreetMap contributors',
    sourceUrl: 'https://www.openstreetmap.org/copyright',
    dataType: 'LIVE',
    updateIntervalSeconds: 86400,
    license: 'ODbL 1.0',
    licenseUrl: 'https://opendatacommons.org/licenses/odbl/',
    sourceAbbrev: 'OSM',
  },
  healthcare: {
    layerKey: 'healthcare',
    sourceName: 'OpenStreetMap contributors',
    sourceUrl: 'https://www.openstreetmap.org/copyright',
    dataType: 'LIVE',
    updateIntervalSeconds: 86400,
    license: 'ODbL 1.0',
    licenseUrl: 'https://opendatacommons.org/licenses/odbl/',
    sourceAbbrev: 'OSM',
  },
  parks: {
    layerKey: 'parks',
    sourceName: 'OpenStreetMap contributors',
    sourceUrl: 'https://www.openstreetmap.org/copyright',
    dataType: 'LIVE',
    updateIntervalSeconds: 86400,
    license: 'ODbL 1.0',
    licenseUrl: 'https://opendatacommons.org/licenses/odbl/',
    sourceAbbrev: 'OSM',
  },
  waste: {
    layerKey: 'waste',
    sourceName: 'OpenStreetMap contributors',
    sourceUrl: 'https://www.openstreetmap.org/copyright',
    dataType: 'LIVE',
    updateIntervalSeconds: 86400,
    license: 'ODbL 1.0',
    licenseUrl: 'https://opendatacommons.org/licenses/odbl/',
    sourceAbbrev: 'OSM',
  },
  mobiData: {
    layerKey: 'mobiData',
    sourceName: 'MobiData BW',
    sourceUrl: 'https://www.mobidata-bw.de/',
    dataType: 'LIVE',
    updateIntervalSeconds: 300,
    license: 'Datenlizenz Deutschland - Namensnennung - Version 2.0',
    licenseUrl: 'https://www.govdata.de/dl-de/by-2-0',
    sourceAbbrev: 'MobiData',
  },
  solarPotential: {
    layerKey: 'solarPotential',
    sourceName: 'LUBW Baden-Wuerttemberg',
    sourceUrl: 'https://www.lubw.baden-wuerttemberg.de',
    dataType: 'STATIC',
    updateIntervalSeconds: null,
    license: 'UIS-Nutzungsvereinbarung',
    licenseUrl: 'https://www.lubw.baden-wuerttemberg.de',
    sourceAbbrev: 'LUBW',
  },
};
